// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JiraWorklogs2019
{
    internal sealed partial class Vsix
    {
        public const string Id = "JiraWorklogs2019.1fa5b220-de94-4ac8-8334-820d662790a8";
        public const string Name = "Jira Worklogs 2019";
        public const string Description = @"This plugin allows you to manage your Jira worklog timers without leaving Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Michael Jordan";
        public const string Tags = "";
    }
}
