// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JiraWorklogs2019
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string JiraWorklogs2019String = "302f828f-19cb-4069-b0f3-76b49e694a4a";
        public static Guid JiraWorklogs2019 = new Guid(JiraWorklogs2019String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int JWCommand = 0x0100;
    }
}